name: Check

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  static-contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Run deterministic checks
        run: make ci
